apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: liveness-pod
  name: liveness-pod
spec:
  containers:
  - image: busybox:stable
    name: liveness-pod
    command: ['sh','-c','while true; do sleep 10; done']
    livenessProbe:
      exec:
        command: ['echo','Health check'] 
      initialDelaySeconds: 5
      periodSeconds: 5
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
