# create mode 100644 exploringVolumes/emptydir-volume-test.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pink-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pink-test
      color: pink
  template:
    metadata:
      labels:
        app: pink-test
        color: pink
    spec:
      containers:
      - name: nginx
        image: linuxacademycontent/ckad-nginx:pink
        ports:
         - containerPort: 80