apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: new-namespace-pod
  name: new-namespace-pod
  namespace: new-namespace
spec:
  containers:
  - image: busybox:stable
    name: new-namespace-pod
    command: ['sh', '-c', 'while true; do echo Running...; sleep 5; done']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
