apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service-server
  name: clusterip-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: service-server
  type: NodePort
status:
  loadBalancer: {}
