apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
spec:
  restartPolicy: Never
  containers:
   - name: busybox
     image: busybox:stable
     command: ['sh', '-c', 'echo $MESSAGE; cat /config/app.cfg'
