apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: broken-pod
  name: broken-pod
spec:
  containers:
  - image: nginx:1.20.q
    name: broken-pod
    livenessProbe:
      httpGet:
        path: /
        port: 81
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
