apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: resources-pod
  name: resources-pod
  namespace: resource-test
spec:
  containers:
  - image: busybox:stable
    name: resources-pod
    command: ['sh', '-c', 'while true; do echo Running...; sleep 5; done']
    resources:
      requests:
        memory: 64Mi
        cpu: 250m
      limits:
        memory: 128Mi
        cpu: 500m
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
